### ISSUE TITLE
late response of button interrupt

### ISSUE THREAD

**Issue by manish5897** [androidthings/sample-simplepio#10]
On very first time button pressed, repsonse not get instantly
Logcat : GPIO changed, button pressed

and so on button pressed response not got instantly.

**Comment by Yanqilong** [comment]
I meet the same problem,  Logcat  print log delayed or not log print when button pressed, So I don't mark sure trigger the edge interrupt

**Comment by manish5897** [comment]
The issue is only with the LOGCAT, gpio status change on every button pressed.

If you add toast rather than logcat, then toast appear every time when you button pressed.
