### ISSUE TITLE
Pin set to output never returns high for getValue.

### ISSUE THREAD

**Issue by Apromixately** [androidthings/sample-simplepio#4]
I have this board http://www.wandboard.org/details/pico-imx6ul and tried the led blinking code but getValue on the gpio pin always returns false. This is true even with nothing connected to the pin so it cannot accidentally be pulled down.

**Comment by mangini** [comment]
getValue() on an output pin returns an unpredictable value, as stated in the [API javadoc](https://developer.android.com/things/reference/com/google/android/things/pio/Gpio.html#getValue())

An early version of this sample relied on getValue(), but it was fixed on this commit: https://github.com/androidthings/sample-simplepio/commit/9c1147d4c34a155b10b6f35fa227bda992551c8a
